name: Deploy API en Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
    deploy: 
      rums-on: ubuntu-22.04
      name: Deploy API to Cloudflare Workers
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 16.15.1
        - uses: pnpm/action-setup@v2
          with:
            version: 7.22.0
            run_intall: true
        - uses: cloudflare/wrangler-action@2.0.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            workingDirectory: api
            args: publish
            