name: Scrapear paguina king league web todos los domingos

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: 0 */1 * * 0

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
      - run: |
          node scraping/leaderboard.js
          git config user.name BOT-MAG
          git add -A
          git commit -m '[bot] Actualizacion BD'
          git push origin main
